### ISSUE TITLE
`muffin new` does not work

### ISSUE THREAD

**Issue by Jeff-Tian** [muffin/cli#58]
Just exit silently without doing nothing.

```
Last login: Mon Jul  4 15:05:54 on ttys002
denmasarus-MacBook-Pro:~ tianjie$ muffin new
denmasarus-MacBook-Pro:~ tianjie$ 
```

**Comment by mtclmn** [comment]
+1

**Comment by kunni80** [comment]
Is this still an issue?
which version of muffin were you using?

**Comment by mtclmn** [comment]
@kunni80 I think it fixed the silent exit issue, but now I get `Error: Cannot find module 'mkdirp'` when running `muffin new`. I checked and mkdirp is in node_modules. Not sure what I'm missing...

**Comment by kifirkin** [comment]
I've got on Windows 7x64

```
muffin\cli\node_modules\args\dist\index.js:329
      throw err;
      ^

Error: spawn index-new ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
```
